### ISSUE TITLE
Amazon Bedrock AgentCore Samples - [Content Improvement]

### ISSUE THREAD

**Issue by pcolazurdo** [awslabs/amazon-bedrock-agentcore-samples#174]
**Describe the improvement request**
I've found some issues when trying to deploy the The SRE Agent example. I'll try to document those here to confirm if they are a bug if it is just some missing documentation. If you confirm these are buggy issues, I can submit a PR to fix them.

 
**What are your suggestions?**

1. the config.yaml.example is missing a configuration parameter: ```credential_provider_name: "sre-agent-api-key-credential-provider"``` as the ```create_gateway.sh``` parameter validation passes and empty parameter which doesn't let main.py use the default paramater (as it is different from None)
2. The ```create_gateway.sh``` script doesn't read some properties correctly and creates a few issues. For example the property  is read past the closing quotation marks and the S3 path is cerated like this:
```
aws ls ${BUCKET}
                           PRE devops-multiagent-demo"  # Path prefix for OpenAPI schema files/
```
3. role_name in config.yaml is not explained. The recommendation would be to leave this empty to CreateGateway can create a role automatically, but the clean up would be harder as this role would be left behind. We could create a new role, but this step should be added to the script.
4. Similar to the point 2, the following line may add  extra characters if not properly copied. In this case it can create the wrong role_name for create_gateway call like this: 
```
CMD+=(--role-arn "arn:aws:iam::${ACCOUNT_ID}:role/${ROLE_NAME}")
example: arn:aws:iam::123456789012 :role/AgentCore-SRE-Agent-Demo -< notice the extra space because the user copied and pasted from the console.
```
Note: the error shown when this happens is an obscure error message: ```botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateGateway operation: User: arn:aws:sts::123456789012:assumed-role/Admin is not authorized to perform: bedrock-agentcore:CreateGateway```

**Additional context**
I can provide a PR to fix this issues as needed.

**Comment by aarora79** [comment]
Thanks @pcolazurdo some of these might be valid, triaging them now. For example point 5 above may not be because we have explicit instructions in the README.md to bind to a private IP, none of the servers listen on `0.0.0.0`. README snippet below:
```
# Get your EC2 instance private IP for server binding
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" -s)
PRIVATE_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" \
  -s http://169.254.169.254/latest/meta-data/local-ipv4)

# Start the demo backend servers with SSL
cd backend
./scripts/start_demo_backend.sh \
  --host $PRIVATE_IP  \
  --ssl-keyfile /etc/ssl/private/privkey.pem \
  --ssl-certfile /etc/ssl/certs/fullchain.pem
```
Will triage and update this issue.

**Comment by pcolazurdo** [comment]
Thanks for triaging. For the case above (private ip) this only works if you are hosting in AgentCore Runtime, but not if you want to test from an ec2 instance (my case) - solution for this may not be needed as my use case may not be the goal of the sample.

**Comment by dheerajoruganty** [comment]
Hi @pcolazurdo!

Thank you for the detailed analysis and thorough testing. I have fixes ready in a branch, and #179 should address these issues. Here's how we've addressed each point, I expect all my changes to be finalized by EOD today:

---

1. Missing credential_provider_name: Fixed and added as default in config.yaml.example.

2. Property parsing in create_gateway.sh: Agreed - reworked the parsing function to handle edge cases properly.

3. role_name documentation: Will add detailed documentation for IAM role creation.

4. Command construction issues: Fixed as part of the shell script improvements in 2.

5. Server accessibility documentation (Let me break it down into 2 things): 
   - I agree that there is missing information on which ports have to be exposed, but there are no specific ports needed for api keys. Will document required port exposure in the deployment guide
   - For this example, we assume the host binding and public IP requirements as user prerequisites.

6. Post-deployment configuration: The README instructions should handle these automatically, but in the case of exporting `GATEWAY_ACCESS_TOKEN` I can verify, but I think that is not a requirement.

7. Model provider configuration: Fixed the configuration precedence and improved error handling.

8. Hard-coded regions: Completely agree, parameterized all regional configurations.

9. Template-based configuration: Great suggestion! We've prioritized backend .yaml files for now and will consider extending this to other configuration files in future updates.

**Comment by pcolazurdo** [comment]
Thanks a lot for these fixes, I think they cover well the issues I faced. I'm happy to test them again once you've submit the fix.
I also found some additional issues when deploying to the AgentCore runtime  but I'll try with all the new changes and submit if I still see some issues.
